# Generated by Django 4.2.1 on 2023-05-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('numero_cuenta', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('tipo_cuenta', models.CharField(max_length=9)),
                ('saldo', models.FloatField()),
            ],
            options={
                'db_table': 'cuentas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('fecha_transaccion', models.DateTimeField()),
            ],
            options={
                'db_table': 'movimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('id_tipo_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_transaccion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'tipo_transaccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titulares',
            fields=[
                ('id_titular', models.AutoField(primary_key=True, serialize=False)),
                ('documento_identidad', models.BigIntegerField()),
                ('tipo_documento', models.CharField(max_length=2)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'titulares',
                'managed': False,
            },
        ),
    ]
